### PR TITLE
unify the coding style of using testcontainers

### PR DESCRIPTION
**Pull request by feuyeux**
To unify the coding style of using testcontainers, and improve maturity for logging

### CODE REVIEW

**Comment by langchain4j** [comment]
Hey @feuyeux thanks a lot and sorry for the delay with review!
I have noticed that there is also this [PR](https://github.com/langchain4j/langchain4j-examples/pull/60) which seems to overlap with yours. Could you please take a look?

**Comment by feuyeux** [comment]
> Hey @feuyeux thanks a lot and sorry for the delay with review! I have noticed that there is also this [PR](https://github.com/langchain4j/langchain4j-examples/pull/60) which seems to overlap with yours. Could you please take a look?

Thanks for reply, and I just checked #60 pull request，there're some files changed on both. What I did is let all series of vector dbs to use log instead of system out, for example, and both of use did unify the coding style on testcontainers. 

So, I can merge this PR if it approved before mine, with pleasure. Or vice versa, maybe :)

**Comment by feuyeux** [comment]
> Hey @feuyeux thanks a lot and sorry for the delay with review! I have noticed that there is also this [PR](https://github.com/langchain4j/langchain4j-examples/pull/60) which seems to overlap with yours. Could you please take a look?

I found

**Comment by feuyeux** [comment]
I found with https://github.com/langchain4j/langchain4j-examples/pull/60 had merged, and then I just merge with it, please review.

**Comment by feuyeux** [comment]
> Hey @feuyeux thanks a lot and sorry for the delay with review! I have noticed that there is also this [PR](https://github.com/langchain4j/langchain4j-examples/pull/60) which seems to overlap with yours. Could you please take a look?

I found that https://github.com/langchain4j/langchain4j-examples/pull/60 had merged, and then I just merge with it, please review.

**Comment by feuyeux** [comment]
@langchain4j Please take a quick look, there's no conflects

**Comment by feuyeux** [comment]
I just created a new PR, and let's move to https://github.com/langchain4j/langchain4j-examples/pull/78.

**Pull request closed without merging**
