### PR TITLE
Enable relatively easy containerization

### PR DESCRIPTION
**Pull request by edburns**
This PR enables easier containerization by adding necessary Dockerfile and updating the Maven build configuration.

# Changes in jakartaee-microprofile-example/pom.xml
- Updated Property Settings:
  - Introduced new properties for plugin versions and compiler settings.
  - Added a new property for HUGGING_FACE_API_KEY to be sourced from environment variables.
- Resource Configuration:
  - Added resource filtering for src/main/resources.
Plugin Management:
   - Added new plugins for Liberty Maven, Maven Compiler, Failsafe, Resources, War, etc.
   - Configured liberty-maven-plugin with execution goals for packaging.
Execution Phases:
   -Configured the maven-resources-plugin for copying Docker and AKS configurations during the validate phase.

# Changes in jakartaee-microprofile-example/src/main/docker/Dockerfile
- Base Image:
   - Set the base image to icr.io/appcafe/open-liberty:23.0.0.12-kernel-slim-java17-openj9-ubi.
- Environment Variable:
   - Added HUGGING_FACE_API_KEY environment variable.
- Configuration and Setup:
   - Copied server.xml and application WAR file to the appropriate directories in the container.
   - Ran scripts to add XML snippets, grow the image, and apply interim fixes.

### CODE REVIEW

**Comment by edburns** [comment]
I seek review from @gkwan-ibm and @GraceJansen .

**Review by langchain4j — APPROVED** [review]
@edburns thank you!

**Comment by langchain4j** [comment]
@edburns sorry, I did not notice the comment regarding review! Please feel free to review anyway and hopefully it will be good. Or I can roll-back this PR, LMK what is better

**Review by gkwan-ibm — COMMENTED** [review]
hi @edburns 
- Why need to add `<param.hugging.face.api.key>${env.HUGGING_FACE_API_KEY}</param.hugging.face.api.key>`? What is the purpose?
- why not use the latest Open Liberty 24.0.0.8 in the pom.xml and Dockerfile?
- why need to add so much configurations in the pom.xml? I think the example for users to learn the basic. That confuses them the app requires a complicated Maven project.
  - `liberty-maven-plugin`, `maven-resources-plugin`

**Comment by gkwan-ibm** [comment]
cc @langchain4j, I post this comment, because the PR was merged, to make sure you got my above comment.

**Comment by edburns** [comment]
Hello @gkwan-ibm it seems I did not follow a process. I also am surprised the PR was merged. Please advise what you want me to do? I can issue a PR with a revert commit if you want.  I had sent Grace a slack message seeking review.

**Comment by gkwan-ibm** [comment]
hi @edburns 

I think the PR owner and revert the PR. There is a `Revert` button. Otherwise, can @langchain4j roll-back this PR in an easy way?

**Comment by gkwan-ibm** [comment]
hi @edburns 

Also, I think we may need to find a channel to discuss what you want to update for the jakartaee-microprofile-example. I don't see that this repo can open an issue for the discussion.

**Pull request merged**
