### PR TITLE
Added Neo4j Content Retriever example

### PR DESCRIPTION
**Pull request by theawesomenayak**
Example for code added in [#685](https://github.com/langchain4j/langchain4j/issues/685)

### CODE REVIEW

**Comment by theawesomenayak** [comment]
@langchain4j please take a look

**Review by jexp — APPROVED** [review]
LGTM

**Comment by theawesomenayak** [comment]
@langchain4j can you please merge this?

**Comment by theawesomenayak** [comment]
@langchain4j it's been 3 weeks now. Can you please merge this?

**Review by langchain4j — APPROVED** [review]
@theawesomenayak thanks!

**Pull request merged**
