### PR TITLE
Add Mistralai examples

### PR DESCRIPTION
**Pull request by czelabueno**
Hi @langchain4j 
I had pending to update MistralAI examples in this repo.

These examples use MistralAI integration added in this [PR#514](https://github.com/langchain4j/langchain4j/pull/514) already released.

Regards!

### CODE REVIEW

**Review by LizeRaes — APPROVED** [review]
Perfect, thanks a lot for adding these examples!

**Review by LizeRaes — APPROVED** [review]

**Comment by czelabueno** [comment]
Great @LizeRaes. It would be great if it could be merged soon. Thank you!

**Comment by langchain4j** [comment]
@czelabueno pardon for the delay. I would remove rag example as there is nothing mistral-specific to RAG, right?
This module is meant to show examples of using Mistral models, as far as inunderstand. For rag, we have rag-examples

**Comment by czelabueno** [comment]
Hi @langchain4j, rag example is basically to demo how implement this mistral [RAG guide](https://docs.mistral.ai/guides/basic-RAG/) using LangChain4j for mistral users. This rag example show how use  mistral embedding model. If you found it duplicated with rag-examples, yeah I can remove it. Just let me know.

**Comment by langchain4j** [comment]
@czelabueno this is not critical, but it indeed seems duplicated. One can do RAG with any combination of embedding models, embedding stores and chat models, etc. Do we really want to create an example (and maintain it) for each combination?

**Comment by LizeRaes** [comment]
I do like the idea of having one chatModel and one embeddingmModel example for each modelprovider that offers them, makes it easier for people that are not deep into the framework to get started with the use case of their choice. I'm afraid if we don't add these examples, we (and they) risk just getting more support questions. Also it is very nice for the providers of the models if they can link directly to both a chatModel example and an embeddingModel one. Just my two cents 😊

**Comment by czelabueno** [comment]
@langchain4j not for each combination, but it will be good to have at least one example for each model type (chat, embedding, etc) supported by LangChain4j.
My thinking is a little more aligned with Lize's. There are users (`user 1`) who first choose the framework and then the model(s) they will use in their chain, but there are also users (`user 2`) from the model provider who look for frameworks to facilitate their integration.
I think that the examples per model provider should guide more to the `user 2` and the general examples (such as rag-examples) to the `user 1`. But of course, this is just my idea of how to document the use of the framework and I could be wrong  😊

**Comment by langchain4j** [comment]
Ok, makes total sense about user1 and user2.

I am just wondering if RAG example should be as detailed as it is now and use low-level components
or better we wrap it into ingestor and use AI service for this?

```
            EmbeddingModel embeddingModel = MistralAiEmbeddingModel.withApiKey(...);

            EmbeddingStore<TextSegment> embeddingStore = new InMemoryEmbeddingStore<>();

            EmbeddingStoreIngestor ingestor = EmbeddingStoreIngestor.builder()
                    .documentSplitter(DocumentSplitters.recursive(300, 0))
                    .embeddingModel(embeddingModel)
                    .embeddingStore(embeddingStore)
                    .build();

            Document document = loadDocument(toPath("example-files/story-about-happy-carrot.txt"), new TextDocumentParser());
            ingestor.ingest(document);
```

Right now it seems too much code and super complicated.
We can of course put a link to a more detailed RAG example.

(I am thinking about how to make the whole RAG thingy very easy for someone withput any prior knowledge and experience.
Like just give it your documents folder and it will do auto-RAG. With some sensible (customizable) defaults.)

**Review by langchain4j — APPROVED** [review]
@czelabueno I am merging it now so that it is not delayed more and more, but we can continue the discussion on how to better document.

**Pull request merged**
