### PR TITLE
Update Elasticsearch example

### PR DESCRIPTION
**Pull request by dadoonet**
* We don't disable security so we use login/password and self signed certificates which is even closer to production ready code
* We use the new 0.34 Elasticsearch embedding store
  - which is now using a rest client
  - and is using the approximate kNN implementation
* We add another example `ElasticsearchEmbeddingStoreWithScriptExample` using the `ElasticsearchConfigurationScript` configuration.
* We call the refresh API instead of waiting for 1s
* We used Elasticsearch 8.15.0 for our tests

### CODE REVIEW

**Comment by dadoonet** [comment]
Once merged, I can update the https://docs.langchain4j.dev/integrations/embedding-stores/elasticsearch page.

**Comment by langchain4j** [comment]
@dadoonet thank you! I will merge it once 0.34.0 is released (next week)

**Comment by dadoonet** [comment]
Please ping me first as I need to change `0.34.0-SNAPSHOT` to `0.34.0` unless you do it by yourself?

**Comment by langchain4j** [comment]
@dadoonet I will do a change myself, no worries!

**Review by langchain4j — APPROVED** [review]
@dadoonet thank you!

**Pull request merged**
